GLOBAL_DOMAINS = [
    "gmail.com",
    "yahoo.com",
    "hotmail.com",
    "outlook.com",
    "mail.com",
    "live.com",
    "icloud.com",
    "aol.com",
    "protonmail.com",
    "zoho.com",
    "yandex.com",
    "gmx.com",
    "me.com",
    "msn.com",
    "mail.ru",
    "inbox.ru",
    "bk.ru",
    "list.ru",
    "rediffmail.com",
    "qq.com",
    "126.com",
    "163.com",
    "sina.com",
    "yeah.net",
    "rocketmail.com",
    "fastmail.com",
    "hushmail.com",
    "tutanota.com",
    "web.de",
    "cox.net",
    "comcast.net",
    "btinternet.com",
    "bellsouth.net",
    "shaw.ca",
    "blueyonder.co.uk",
    "virginmedia.com",
    "optonline.net",
    "wanadoo.fr",
    "orange.fr",
    "seznam.cz",
]

POLISH_DOMAINS = [
    "wp.pl",
    "onet.pl",
    "o2.pl",
    "interia.pl",
    "gazeta.pl",
    "tlen.pl",
    "op.pl",
    "poczta.fm",
    "autograf.pl",
    "buziaczek.pl",
    "vp.pl",
    "go2.pl",
    "home.pl",
    "prokonto.pl",
    "neostrada.pl",
    "amorki.pl",
    "konto.pl",
    "poczta.onet.pl",
    "inetia.pl",
    "email.pl",
]

FEATURE_DESCRIPTIONS = [
    "150 Gems bonus",
    "300 Gems bonus",
    "500 Gems bonus",
    "750 Gems bonus",
    "1000 Gems bonus",
    "Double XP for 1 hour",
    "Double XP for 2 hours",
    "Double XP for 4 hours",
    "Instant cooldown for 1 spell",
    "Instant cooldown for 2 spells",
    "Instant cooldown for all spells",
    "Premium Battle Pass access",
    "Elite Skin Pack: 'Dragon Slayer'",
    "Exclusive Pet: 'Mini Golem'",
    "Boost: +5% Gold drop for 24h",
    "Boost: +10% Gold drop for 24h",
    "Boost: +15% Gold drop for 24h",
    "Boost: +5% Item drop for 24h",
    "Boost: +10% Item drop for 24h",
    "Boost: +15% Item drop for 24h",
    "Additional inventory slot (permanent)",
    "Additional 2 inventory slots (permanent)",
    "Additional 3 inventory slots (permanent)",
    "Unlock 'Shadow' character class",
    "Unlock 'Alchemist' character class",
    "Unique Avatar Frame: 'Mystic Aura'",
    "Unique Profile Background: 'Cosmic Dust'",
    "5x Minor Health Potion",
    "10x Minor Health Potion",
    "5x Major Mana Potion",
    "10x Major Mana Potion",
    "Skip 1 level up timer",
    "Skip 2 level up timers",
    "Skip 5 level up timers",
    "Crafting speed +25% for 12h",
    "Crafting speed +50% for 12h",
    "Resource pack: Wood (Small)",
    "Resource pack: Stone (Medium)",
    "Resource pack: Iron (Large)",
    "Daily Login Bonus multiplier x2 for 3 days",
    "Daily Login Bonus multiplier x3 for 3 days",
    "Rename character token",
    "Guild creation discount (50%)",
    "Fast travel discount (24h)",
    "Limited-edition Emote Pack",
    "Enchanted pickaxe (temporary)",
    "Legendary fishing rod (temporary)",
    "Resurrection Orb (single use)",
    "Auto-loot for 30 minutes",
    "Increased critical hit chance for 1 battle",
]

FEATURE_PRICES = [
    3, 6, 9, 12, 15, 5, 9, 14, 2, 4, 8, 15, 12, 10, 4, 7, 11, 5, 9, 13,
    6, 10, 14, 15, 15, 8, 7, 1, 2, 3, 5, 4, 7, 12, 6, 10, 2, 5, 9, 8, 13,
    7, 10, 5, 9, 6, 8, 15, 11, 3,
]

EXTRA_DESCRIPTIONS = [
    "three additional moves",
    "five additional moves",
    "bronze treasure chest",
    "silver treasure chest",
    "gold treasure chest",
]

EXTRA_PRICES = [4, 8, 2, 4, 8]

APP_INFO_TYPES = [
    "name_surname",
    "email",
    "users_from_city",
    "has_user_cc",
    "extras_per_user",
    "features_per_user",
    "get_addons_per_user",
    "get_extras_per_time",
    "get_user_transactions",
]

# Made with Bob
